### ISSUE TITLE
ClientRepositoryInterface is not instantiable while building 

### ISSUE THREAD

**Issue by marcio81** [mikemclin/passport-custom-request-grant#3]
After install and implement show this error for whatever i done (Postman, migrate...): Illuminate\Contracts\Container\BindingResolutionException: Target [League\OAuth2\Server\Repositories\ClientRepositoryInterface] is not instantiable while building [League\OAuth2\Server\AuthorizationServer]. in /var/www/wa/clean-api/vendor/illuminate/container/Container.php:763.

And what is exactly this "bySsoToken"? 

My Custon provider

`use Laravel\Passport\Bridge\RefreshTokenRepository;
use Laravel\Passport\Bridge\UserRepository;
use Laravel\Passport\Passport;
use Laravel\Passport\PassportServiceProvider;
use League\OAuth2\Server\AuthorizationServer;
use League\OAuth2\Server\Grant\PasswordGrant;
/**
 * Class CustomQueueServiceProvider
 *
 * @package App\Providers
 */
class SSOGrantProvider extends PassportServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        //$ClientInterface = app()->make('WA\vendor\league\oauth2-server\Repositories\ClientRepositoryInterface');
    }
    /**
     * Register the service provider.
     *
     * @return void
     */
    public function register()
    {
       
        app(AuthorizationServer::class)->enableGrantType($this->makeSSOGrant(), Passport::tokensExpireIn());
    }
    /**
     * Create and configure a Password grant instance.
     *
     * @return PasswordGrant
     */
    protected function makeSSOGrant()
    {
        $grant = new SSOGrant(
            $this->app->make(UserRepository::class),
            $this->app->make(RefreshTokenRepository::class)
        );
        $grant->setRefreshTokenTTL(Passport::refreshTokensExpireIn());
        return $grant;
    }
}`

Model

`use Illuminate\Http\Request;
use Laravel\Passport\Bridge\User;
use League\OAuth2\Server\Entities\UserEntityInterface;
use League\OAuth2\Server\Exception\OAuthServerException;
use League\OAuth2\Server\Grant\AbstractGrant;
use League\OAuth2\Server\Repositories\RefreshTokenRepositoryInterface;
use League\OAuth2\Server\Repositories\UserRepositoryInterface;
use League\OAuth2\Server\RequestEvent;
use League\OAuth2\Server\ResponseTypes\ResponseTypeInterface;
use Psr\Http\Message\ServerRequestInterface;

/**
 * SSO grant class.
 */
class SSOGrant extends AbstractGrant
{
/**
     * @param UserRepositoryInterface         $userRepository
     * @param RefreshTokenRepositoryInterface $refreshTokenRepository
     */
    public function __construct(
        UserRepositoryInterface $userRepository,
        RefreshTokenRepositoryInterface $refreshTokenRepository
    )
    {
        $this->setUserRepository($userRepository);
        $this->setRefreshTokenRepository($refreshTokenRepository);
        $this->refreshTokenTTL = new \DateInterval('P1M');
    }
    /**
     * {@inheritdoc}
     */
    public function respondToAccessTokenRequest(
        ServerRequestInterface $request,
        ResponseTypeInterface $responseType,
        \DateInterval $accessTokenTTL
    )
    {
        // Validate request
        $client = $this->validateClient($request);
        $scopes = $this->validateScopes($this->getRequestParameter('scope', $request));
        $user = $this->validateUser($request);
        // Finalize the requested scopes
        $scopes = $this->scopeRepository->finalizeScopes($scopes, $this->getIdentifier(), $client, $user->getIdentifier());
        // Issue and persist new tokens
        $accessToken = $this->issueAccessToken($accessTokenTTL, $client, $user->getIdentifier(), $scopes);
        $refreshToken = $this->issueRefreshToken($accessToken);
        // Inject tokens into response
        $responseType->setAccessToken($accessToken);
        $responseType->setRefreshToken($refreshToken);
        return $responseType;
    }
    /**
     * {@inheritdoc}
     */
    public function getIdentifier()
    {
        return 'sso';
    }
    /**
     * @param ServerRequestInterface $request
     *
     * @return UserEntityInterface
     * @throws OAuthServerException
     */
    protected function validateUser(ServerRequestInterface $request)
    {
        $laravelRequest = new Request($request->getParsedBody());
        $user = $this->getUserEntityByRequest($laravelRequest);
        if ($user instanceof UserEntityInterface === false) {
            $this->getEmitter()->emit(new RequestEvent(RequestEvent::USER_AUTHENTICATION_FAILED, $request));
            throw OAuthServerException::invalidCredentials();
        }
        return $user;
    }
    /**
     * Retrieve user by request.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Laravel\Passport\Bridge\User|null
     * @throws \League\OAuth2\Server\Exception\OAuthServerException
     */
    protected function getUserEntityByRequest(Request $request)
    {
        if (is_null($model = config('auth.providers.users.model'))) {
            throw OAuthServerException::serverError('Unable to determine user model from configuration.');
        }
        if (method_exists($model, 'byPassportSSOGrantRequest')) {
            $user = (new $model)->byPassportSSOGrantRequest($request);
        } else {
            throw OAuthServerException::serverError('Unable to find byPassportSSOGrantRequest method on user model.');
        }
        return ($user) ? new User($user->id) : null;
    }
}`
User functions

`public function byPassportSSOGrantRequest(Request $request)
{
    try {
        if ($request->get('sso')) {
            return $this->SSOGrantVerify($request->get('sso'));
            
        }
    } catch (\Exception $e) {
        throw OAuthServerException::accessDenied($e->getMessage());
    }
    return null;
}

     public function SSOGrantVerify(Request $request)
    {
        
        $laravelUser = Cache::get('saml2user_'.$request);

        if (!isset($laravelUser)) {
            return false;
        } else {
            return $laravelUser['attributes'];
        }
    }
}
`

**Comment by marcio81** [comment]
Dig in the error y found a problem in: 

`protected function makeSSOGrant()
    { 
        $grant = new \WA\Auth\SSOGrant(
          Log::debug("test1: ".print_r($this->app->make(UserRepository::class), true)),

```
        Log::debug("test3: ".print_r( $this->app->make(RefreshTokenRepository::class), true)),
        dd("END"),

        $this->app->make(UserRepository::class),
       this line --> $this->app->make(RefreshTokenRepository::class)
    );

    $grant->setRefreshTokenTTL(Passport::refreshTokensExpireIn());
    return $grant;
}`
```

[2016-11-17 09:26:50] lumen.ERROR: Illuminate\Contracts\Container\BindingResolutionException: Unresolvable dependency resolving [Parameter #0 [ <required> $pdo ]] in class Illuminate\Database\Connection in /var/www/wa/clean-api/vendor/illuminate/container/Container.php:850

**Comment by mikemclin** [comment]
`bySsoToken` is just used as an example in the README file.  It is an example of how an app might implement the custom grant.  It is not actually part of the codebase.

**Comment by marcio81** [comment]
tks but that i know :) . Anyway i already solve this issue.
